---
booktitle: Proceedings on ``{I} Can't Belive It's Not Better!'' at {NeurIPS} Workshop
shortname: ICBINB
year: '2020'
start: 2020-12-12
end: 2020-12-12
published: 2020-02-08
url: http://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ICBINB2020
month: 0
cycles: false
title: Proceedings of Machine Learning Research
description: |
  Proceedings on ``{I} Can't Belive It's Not Better!'' at {NeurIPS} Workshop
    Held in NeurIPS Workshop, Virtual on 12 December 2020

  Published as Volume 137 by the Proceedings of Machine Learning Research on 08 February 2020.

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 12 Dec
author:
  name: PMLR
baseurl: "/v137"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v137
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume: 137
email: ''
conference:
  name: "``I Can't Belive It's Not Better!'' at {NeurIPS} Workshop"
  url: 
  location: NeurIPS Workshop, Virtual
  dates:
  - 2020-12-12
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v137/icbinb2020.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v137/icbinb2020.bib
